version: '{build}'
clone_folder: C:\gopath\src\github.com\xor-gate\go-bjf
environment:
  GOPATH: C:\gopath
build_script:
- cmd: go version
- cmd: go env
- cmd: go get -v github.com/xor-gate/go-bjf/...
- cmd: go build github.com/xor-gate/go-bjf
test_script:
- cmd: go test -v github.com/xor-gate/go-bjf
