go_import_path: github.com/xor-gate/go-bjf
language: go
sudo: false
go:
  - 1.3
  - 1.4
  - 1.5
  - tip
install:
  - go get golang.org/x/tools/cmd/vet
script:
  - make tools
  - make lint
  - make test
  - make bench
